version: '3'
services:
  yuzu_emu:
    tty: true
    image: yuzu_emu:latest
    privileged: true
    runtime: nvidia
    container_name: yuzu_emu
    ports:
      - "8081:8081"
      - "6006:6006"
    volumes:
      - "/Users/ruihirano/MyProjects/DeepSmashProject/:/workspace"
      - "/Users/ruihirano/MyProjects/DeepSmashProject/data/keys:/root/.local/sh\
        are/yuzu/keys"
    environment:
      - "RESOLUTION=1280x720"
      - "VNCPASS=pass"
      - "DISPLAY=:1"
